before_script:
  - apt-get -y update 
  - apt-get -y install software-properties-common
  - apt-add-repository -y ppa:ansible/ansible
  - apt-get -y update
  - apt-get -y install ansible
  - ansible --version

stages:
  - build

job1:
  stage: build
  script:
    - ansible-playbook Playbook.yml
  only:
    - master
  tags:
    - ansible

